urls.py
from django.conf.urls import url

from . import views

app_name = 'directorio'

urlpatterns=[
	url(r'^$', views.index, name='index'),
	url(r'^(?P<minion_id>[0-9]+)/$', views.detalle, name='detalle'),
]

models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Minion(models.Model):
	nombre_texto = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.nombre_texto

views.py
from django.shortcuts import get_object_or_404, render
from .models import Minion

import salt.client
import salt.config
import salt.loader
# Create your views here.
def index(request):
	latest_question_list = Minion.objects.order_by('-pub_date')[:5]
	local = salt.client.LocalClient()
    	nombre=local.cmd('*', 'cmd.run', ['whoami'])
    	context = {'latest_question_list': latest_question_list, 'nombre':nombre}
    	return render(request, 'indice.html', context)
def detalle(request, minion_id):
	minion = get_object_or_404(Minion, pk=minion_id)
	__opts__ = salt.config.minion_config('/etc/salt/minion')
	__grains__ = salt.loader.grains(__opts__)
	__opts__['grains'] = __grains__
	__utils__ = salt.loader.utils(__opts__)
	__salt__ = salt.loader.minion_mods(__opts__, utils=__utils__)
	x=__salt__['service.status']('nginx')
	context = {'minion': minion, 'x':x}
    	return render(request, 'detalle.html', context)

templates/detalle.html
<html>
	<head>
		{% load staticfiles %}

		<link rel="stylesheet" type="text/css" href="{% static 'configuracion/style.css' %}" />
		<title>Detalles</title>
	</head>
	<body> 

		<h1> Nombre: {{minion.nombre_texto}} </h1>
		<p> {{x}}</p>
		<a href="{% url 'directorio:index' %}">Indice</a>

		
	</body>
</html>

templates/indice.html
<html>
	<head>
		{% load staticfiles %}

		<link rel="stylesheet" type="text/css" href="{% static 'configuracion/style.css' %}" />
		<title>Indice</title>
	</head>
	<body> 

	{% if latest_question_list %}
	    <ul>
	    {% for minion in latest_question_list %}
		<li><a href="{% url 'directorio:detalle' minion.id %}">{{ minion.nombre_texto }}</a></li>
	    
	    {% endfor %}

	    </ul>
	{% else %}
	    <p>No hay minions.</p>
	{% endif %}
	<p>Su nombre es {{ nombre }} </p>
	</body>
</html>